[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://skyelectrotechweb.onrender.com/api"
  VITE_APP_NAME = "SkyElectroTech"
  VITE_APP_VERSION = "1.0.0"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, immutable, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[redirects]]
  from = "/api/sitemap.xml"
  to = "https://skyelectrotechweb.onrender.com/api/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/api/robots.txt"
  to = "https://skyelectrotechweb.onrender.com/api/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


