name: Build & Deploy Frontend to AWS S3

on:
  push:
    branches:
      - master  # or 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Set environment variables
        run: |
          echo "VITE_API_URL=https://api.skyelectrotech.in/api" >> $GITHUB_ENV
          echo "VITE_APP_NAME=SkyElectroTech" >> $GITHUB_ENV
          echo "VITE_APP_VERSION=1.0.0" >> $GITHUB_ENV

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Verify build output
        run: |
          echo "Build completed. Checking dist folder contents:"
          ls -la ./frontend/dist/
          test -f ./frontend/dist/index.html && echo "✓ index.html found" || echo "✗ index.html missing"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./frontend/dist/ s3://skyelectrotech-files/ --delete \
            --exact-timestamps

          # Set correct content-types for static assets
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.html" --content-type "text/html" --cache-control "no-cache"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.js" --content-type "application/javascript" --cache-control "max-age=31536000"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.css" --content-type "text/css" --cache-control "max-age=31536000"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.json" --content-type "application/json" --cache-control "max-age=86400"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.png" --content-type "image/png" --cache-control "max-age=31536000"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.jpg" --include "*.jpeg" --content-type "image/jpeg" --cache-control "max-age=31536000"
          aws s3 cp ./frontend/dist/ s3://skyelectrotech-files/ --recursive --exclude "*" --include "*.svg" --content-type "image/svg+xml" --cache-control "max-age=31536000"

          # Enable static website hosting
          aws s3 website s3://skyelectrotech-files --index-document index.html --error-document index.html

      - name: Configure S3 bucket policy for public access
        run: |
          cat > bucket-policy.json << EOF
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Sid": "PublicReadGetObject",
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::skyelectrotech-files/*"
              }
            ]
          }
          EOF

          aws s3api put-bucket-policy --bucket skyelectrotech-files --policy file://bucket-policy.json
