name: Build & Deploy Frontend to AWS S3

on:
  push:
    branches:
      - master  # Change to main if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'
          
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
        
      - name: Build frontend
        run: npm run build
        working-directory: ./frontend
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
          
      # Option 1: Safe sync (no deletion)
      - name: Deploy to S3 (Safe - No Deletion)
        run: |
          aws s3 sync ./frontend/dist s3://skyelectrotech-files --acl public-read
          
      # Option 2: Deploy to specific folder to avoid conflicts
      # - name: Deploy to S3 (Specific Folder)
      #   run: |
      #     aws s3 sync ./frontend/dist s3://skyelectrotech-files/app/ --acl public-read
          
      # Option 3: Deploy with exclusions (uncomment and modify as needed)
      # - name: Deploy to S3 (With Exclusions)
      #   run: |
      #     aws s3 sync ./frontend/dist s3://skyelectrotech-files \
      #       --acl public-read \
      #       --exclude "assets/*" \
      #       --exclude "images/*" \
      #       --exclude "*.pdf"