name: Build & Deploy Frontend to AWS S3

on:
  push:
    branches:
      - master  # Change to main if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build frontend
        run: npm run build
        working-directory: ./frontend

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.6.0
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: skyelectrotech-files
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-north-1
          SOURCE_DIR: ./frontend/dist
